name: Foundry CI

on:
  push:
    branches: [main, feat/*]
  pull_request:
    branches: [main]

jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ github.token }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Force update submodules
        run: git submodule update --init --recursive

      - name: Run Foundry Tests
        run: forge test -vvv